name: "ICU4C Meson"

on:
    push:
    pull_request:

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y python3 ninja-build meson
      - run: |
            cd icu4c
            meson setup build
            cd build
            meson compile
            meson test
