name: "ICU4C Meson"

on:
    push:
    pull_request:

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: meson setup
        run: sudo apt-get install -y python3 ninja-build meson
      - name: meson compile
        run: |
            cd icu4c
            meson setup build
            cd build
            meson compile
      - name: meson test
        run: |
            cd icu4c/build && meson test -v
